# Generated by Django 4.1.6 on 2023-03-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Proyecto Coder', max_length=255),
        ),
    ]
